input{
    jdbc {
        jdbc_driver_library => "/home/python/mysql-connector-java-8.0.13/mysql-connector-java-8.0.13.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        jdbc_connection_string => "jdbc:mysql://127.0.0.1:3306/lawyer_ol?tinyInt1isBit=false"
        jdbc_user => "root"
        jdbc_password => "mysql"
        jdbc_paging_enabled => "true"
        jdbc_page_size => "1000"
        jdbc_default_timezone =>"Asia/Shanghai"
        statement => "select a.qust_id as qustion_id,a.user_id as asker_id, a.title as title, a.expertise_id as expertise_id, a.city_id as city_id, a.status as status, a.create_time as create_time,  b.content as content from question_basic as a inner join question_content as b on a.qust_id=b.qust_id"
        use_column_value => "true"
        tracking_column => "qust_id"
        clean_run => true
    }
}
output{
    elasticsearch {
        hosts => "127.0.0.1:9200"
        index => "qusts"
        document_id => "%{qustion_id}"
        document_type => "qust"
    }
    stdout {
        codec => json_lines
    }
}
