[pytest]
; 空格分隔，可添加多个命令行参数
addopts = -s --html=./reports/report.html --reruns 2
;把测试脚本放在scrip文件夹
testpaths = ./scripts
;以test_开头，以.py结尾的所有文件
python_files = test*.py
;当前目录下的scripts文件夹下，以Test开头
python_classes = Test*
;Test_开头的类内，以test_开头的⽅法都会执行
python_functions = test_*
