@echo off
chcp 65001 >nul
echo [1/6] Installing dependencies...
pip install huggingface_hub
echo [2/6] Running distribution script...
python scripts/distribute_files.py
echo [3/6] Adding files to Git...
git add .
echo [4/6] Committing...
git commit -m "Auto: Update files (Dual-Storage)"
echo [5/6] Pushing to GitHub...
git push origin main
pause
